#!/bin/bash
# Crème Rappel
# Hans Fugal
# GPL2

## Customization
SPEAK=true
GROWL=true
GROWLNOTIFY=`which growlnotify`
GROWL_ICON='-a iCal.app'      # See growlnotify(1) and watch the quoting
GROWL_NAME='Crème Rappel'
SHOW_TIME=false  # show the time specification in the growl notification
#SAY_VOICE='Zarvox'
##

DEBUG=false

usage() {
    cat <<EOF
usage: $0 [time [message]]

time is in the format that at(1) expects.

If message or both are not specified, they are expected on stdin. If neither is
specified, multiple time message pairs are accepted on stdin.
EOF
}

growl_at() {
    MSG=`cat`
    TIME=$1
    $SHOW_TIME && APPEND=" ($TIME)"
    [ -z "$SAY_VOICE" ] || VOICE="-v \"$SAY_VOICE\""
    COMMANDS="
        $SPEAK && say $VOICE \"$MSG\" &
        # the -w is necessary because of a bug in growl or growlnotify on
        # Leopard
        $GROWL && \
          $GROWLNOTIFY -w -s -n \"$GROWL_NAME\" $GROWL_ICON -m \"$MSG$APPEND\" &
    "
    $DEBUG && echo "$COMMANDS"

    echo "$COMMANDS" | at "$TIME"
}

if [ "x$1" = 'x-h' ]; then
    usage
    exit
fi

if [ $# -eq 0 ]; then
    # No arguments
    while read i; do 
        TIME=`echo $i | cut -f 1 -d ' '`
        MSG=`echo $i | cut -f 2- -d ' '`
        echo "$MSG" | growl_at "$TIME"
    done
elif [ $# -eq 1 ]; then
    # One argument (time)
    cat | growl_at "$1"
else
    # More than one (time and message pairs)
    TIME=$1
    shift
    echo "$@" | growl_at "$TIME"
fi

# Copyright (C) 2008  Hans Fugal
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
