#!/bin/bash
# Crème Rappel
# Hans Fugal
# GPL2

## Customization
ICON='-a iCal.app'      # See growlnotify(1)
SPEAK=true
GROWL=true
GROWLNOTIFY=`which growlnotify`
NAME='Crème Rappel'

usage() {
    cat <<EOF
usage: $0 [time [message]]

time is in the format that at(1) expects.

If message or both are not specified, they are expected on stdin. If neither is
specified, multiple time message pairs are accepted on stdin.
EOF
}

growl_at() {
    MSG=`cat`
    cat <<EOF | at "$1"
        $SPEAK && say "$MSG" &
        # the -w is necessary because of a bug in growl or growlnotify on
        # Leopard
        $GROWL && $GROWLNOTIFY-w -s -n $NAME $ICON -m "$MSG" &
EOF
}

if [ $# -eq 0 ]; then
    # No arguments
    while read i; do 
        TIME=`echo $i | cut -f 1 -d ' '`
        MSG=`echo $i | cut -f 2- -d ' '`
        echo "$MSG" | growl_at "$TIME"
    done
elif [ $# -eq 1 ]; then
    if [ "$1" = '-h' ]; then
        usage
        exit
    fi

    # One argument (time)
    cat | growl_at "$1"
else
    # More than one (time and message pairs)
    TIME=$1
    shift
    echo "$@" | growl_at "$TIME"
fi

# Copyright (C) 2008  Hans Fugal
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
